# docker-compose.yml
version: "3"
services:
  app:
    env_file: .env
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=postgres_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: "always"
    ports:
      - "5432:5432"
